export const ERROR_CODES = {
  DEMO_INVALID_ROLE: "DEMO_INVALID_ROLE",
  DEMO_INIT_FAILED: "DEMO_INIT_FAILED",
  DEMO_START_FAILED: "DEMO_START_FAILED",
  CONDO_CNPJ_REQUIRED: "CONDO_CNPJ_REQUIRED",
  CONDO_CNPJ_INVALID: "CONDO_CNPJ_INVALID",
  CONDO_NOT_FOUND: "CONDO_NOT_FOUND",
  AUTH_REQUIRED_FIELDS: "AUTH_REQUIRED_FIELDS",
  AUTH_INVALID_PASSWORD_FORMAT: "AUTH_INVALID_PASSWORD_FORMAT",
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_CNPJ_ALREADY_EXISTS: "AUTH_CNPJ_ALREADY_EXISTS",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_BLOCKED: "AUTH_USER_BLOCKED",
  AUTH_PENDING_APPROVAL: "AUTH_PENDING_APPROVAL",
  AUTH_NOT_AUTHENTICATED: "AUTH_NOT_AUTHENTICATED",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_SESSION_INVALID: "AUTH_SESSION_INVALID",
  ACCOUNT_NAME_REQUIRED: "ACCOUNT_NAME_REQUIRED",
  ACCOUNT_EMAIL_IN_USE: "ACCOUNT_EMAIL_IN_USE",
  PASSWORD_REQUIRED_FIELDS: "PASSWORD_REQUIRED_FIELDS",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_CURRENT_INVALID: "PASSWORD_CURRENT_INVALID",
  ACCOUNT_DELETE_FORBIDDEN: "ACCOUNT_DELETE_FORBIDDEN",
  SERVER_INTERNAL_ERROR: "SERVER_INTERNAL_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export function sendError(res: any, status: number, code: ErrorCode, message: string, extra?: Record<string, unknown>) {
  res.status(status).json({ code, error: message, ...extra });
}